version: '3.8'

services:
  inference:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FLASK_PORT:-5000}:5000"  # Expose the port for the video feed
    environment:
      - VIDEO_DEVICE_INDEX=${VIDEO_DEVICE_INDEX:-0}
      - CAMERA_TYPE=usb
      - CAMERA_ID=${CAMERA_ID:-jetson1}
      - DB_HOST=${DB_HOST:-192.168.1.100}
      - DB_NAME=${DB_NAME:-detections_db}
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_PORT=${DB_PORT:-5432}
      - ROBOFLOW_MODEL_URL=${ROBOFLOW_MODEL_URL:-http://192.168.1.100:9001/construction-safety-gsnvb/1}
    devices:
      - /dev/video${VIDEO_DEVICE_INDEX:-0}:/dev/video${VIDEO_DEVICE_INDEX:-0}
    volumes:
      - ../detections:/app/detections
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  detections: