version: '3.8'

services:
  postgres:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-detections_db}
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  roboflow-inference:
    image: roboflow/roboflow-inference-server-gpu:latest
    ports:
      - "${ROBOFLOW_PORT:-9001}:9001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - app-network

  inference:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${INFERENCE_PORT:-5001}:5000"  # Expose a different port for inference
    environment:
      - VIDEO_DEVICE_INDEX=${VIDEO_DEVICE_INDEX:-0}
      - CAMERA_TYPE=usb
      - CAMERA_ID=${CAMERA_ID:-host_camera}
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME:-detections_db}
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_PORT=${DB_PORT:-5432}
      - ROBOFLOW_MODEL_URL=${ROBOFLOW_MODEL_URL:-http://roboflow-inference:9001/construction-safety-gsnvb/1}
    devices:
      - /dev/video${VIDEO_DEVICE_INDEX:-0}:/dev/video${VIDEO_DEVICE_INDEX:-0}
    volumes:
      - ../detections:/app/detections
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - postgres
      - roboflow-inference
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FLASK_PORT:-5000}:5000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME:-detections_db}
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_PORT=${DB_PORT:-5432}
      - ROBOFLOW_MODEL_URL=${ROBOFLOW_MODEL_URL:-http://roboflow-inference:9001/construction-safety-gsnvb/1}
      - JETSON_HOST=${JETSON_HOST:-http://192.168.1.101:5000}
      - LOCAL_INFERENCE_HOST=${LOCAL_INFERENCE_HOST:-http://inference:5000}
    depends_on:
      - postgres
      - roboflow-inference
    volumes:
      - ../detections:/app/detections
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  detections: